// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:a273abf3-0d70-46aa-85fe-0c2e1a3569e1",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_O7sVtTlSf",
    "aws_user_pools_web_client_id": "6fou152bu1sqpkvgn0mfgal2i6",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "posts-socialapp",
            "region": "eu-central-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "postAPI",
            "endpoint": "https://4ukwqzy8yl.execute-api.eu-central-1.amazonaws.com/socialapp",
            "region": "eu-central-1"
        }
    ],
    "aws_content_delivery_bucket": "socialpp-20191018213613-hostingbucket-socialapp",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://dk4obxuby5cdg.cloudfront.net"
};


export default awsmobile;
