// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'eu-central-1:37d60ac2-476d-470a-881f-6f76eadcd442';
var aws_cognito_region = 'eu-central-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'angulartestapp-hosting-mobilehub-430262571';
var aws_content_delivery_bucket_region = 'eu-central-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd3l3kr7lx0f8c2.cloudfront.net';
var aws_mobile_analytics_app_id = '86c1ce7b32af49408d05c9346cb74bfe';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'dc41b38b-9756-49fc-9078-043e764b28cc';
var aws_project_name = 'angular-test-app';
var aws_project_region = 'eu-central-1';
var aws_resource_name_prefix = 'angulartestapp-mobilehub-430262571';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
